# Generated by Django 4.2.30 on 2026-04-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва послуги')),
                ('description', models.TextField(verbose_name='Опис')),
                ('image', models.ImageField(blank=True, null=True, upload_to='corporate/', verbose_name='Фонове зображення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Корпоративна послуга',
                'verbose_name_plural': 'Корпоративні послуги',
            },
        ),
    ]
