# Generated by Django 4.2.30 on 2026-04-22 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Зображення')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('order', models.IntegerField(default=0, verbose_name='Сортування')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва страви')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ціна')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='dishes/', verbose_name='Головне зображення')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярна страва')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наявності')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='menu.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Страва',
                'verbose_name_plural': 'Страви',
            },
        ),
        migrations.CreateModel(
            name='DishImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dishes/gallery/', verbose_name='Додаткове зображення')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='menu.dish', verbose_name='Страва')),
            ],
            options={
                'verbose_name': 'Фото страви',
                'verbose_name_plural': 'Галерея страв',
            },
        ),
    ]
