# Generated by Django 4.2.30 on 2026-04-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Cezar', max_length=200, verbose_name='Головний заголовок')),
                ('subtitle', models.CharField(default='Справжня родинна гостинність', max_length=300, verbose_name='Підзаголовок')),
                ('image', models.ImageField(upload_to='hero/', verbose_name='Фонове зображення (на весь екран)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Головний Банер',
                'verbose_name_plural': 'Головний Банер',
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='calories',
            field=models.IntegerField(blank=True, null=True, verbose_name='Калорійність (ккал)'),
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.TextField(blank=True, verbose_name='Склад страви'),
        ),
        migrations.AddField(
            model_name='dish',
            name='weight',
            field=models.CharField(blank=True, max_length=50, verbose_name="Вага / Об'єм"),
        ),
    ]
