# Generated by Django 4.2.30 on 2026-04-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_herobanner_dish_calories_dish_ingredients_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Фотографія')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Короткий підпис')),
                ('order', models.IntegerField(default=0, verbose_name='Сортування (порядок)')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Відображати на сайті')),
            ],
            options={
                'verbose_name': 'Фото для галереї',
                'verbose_name_plural': 'Галерея',
                'ordering': ['order', '-id'],
            },
        ),
    ]
